runtime: nodejs20
env: standard
service: backend

entrypoint: npm run start:prod

env_variables:
  GCP_BUCKET_NAME: "codit-test-bucket"  # <-- Set your actual bucket name here

handlers:
  - url: /.*
    script: auto