steps:
  - name: "gcr.io/cloud-builders/npm"
    dir: "backend"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    dir: "backend"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "app",
      "deploy",
      "backend/app.yaml",
      "--project=codit-luxembourg",
      "--quiet"
    ]
    timeout: "20000s"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET


images: []